#!/bin/bash
if [ "$(whoami)" == "runner" ]; then
  echo "We are on GitHub, so don't run lint manually"
else
  echo "Running locally because we don't think we are on GitHub"
  rm "$( dirname -- "$0"; )"/../super-linter.log
  "$( dirname -- "$0"; )"/lint
fi
